version: '3.3'

services:
  mysql:
    image: 'mysql/mysql-server:8.0'
    ports:
        - '3306:3306'
    environment:
        MYSQL_ROOT_PASSWORD: 'password'
        MYSQL_ROOT_HOST: "%"
        MYSQL_DATABASE: 'barcode'
        MYSQL_USER: 'root'
        MYSQL_PASSWORD: 'password'
    volumes:
        - 'mysql:/var/lib/mysql'
        - './docker/init-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
    healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
        retries: 3
        timeout: 5s
    networks:
      - barcode
  rocket:
    build: .
    # command: bash -c "cargo run"
    links:
      - mysql
    ports:
      - 8080:8080
    networks:
        - barcode

networks:
   barcode:
        external: true
volumes:
    mysql:
        driver: local